name: Build Loop

on:
  workflow_dispatch: 
  push:
    branches:
      - develop
    paths:
      - Loop/**

jobs:
  build_with_signing:
    name: Build Loop
    runs-on: macos-13

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.5.3
    
      - name: Switch Xcode version
        run: |
          sudo xcode-select -s "/Applications/Xcode_15.0.app"
          /usr/bin/xcodebuild -version
          
      - name: Codesign Loop.app
        uses: apple-actions/import-codesign-certs@v2
        with: 
          p12-file-base64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
          p12-password: ${{ secrets.P12_PASSWORD }}
          
      - name: Build Loop.app
        run: |
          sh ./resources/build_loop.sh

      - name: Zip Loop.app
        run: |
          ditto -c -k --sequesterRsrc --keepParent Loop.app Loop.zip
      
      - name: Upload achived app
        uses: actions/upload-artifact@v3.1.2
        with:
          name: Loop.zip
          path: Loop.zip
      
      - name: Make release notes
        run: |
          sha_short=$(git rev-parse --short HEAD)
          echo $sha_short: ${{ github.event.head_commit.message }} > Release.txt
          
          # Check Release Notes
          cat Release.txt
      
#       - name: Publish Prerelease
#         uses: softprops/action-gh-release@v1
        
