name: Build Loop

on:
  workflow_dispatch: 
  push: 

jobs:
  build_with_signing:
    name: Build Loop
    runs-on: macos-13

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.5.3
    
      - name: Switch Xcode version
        run: |
          sudo xcode-select -s "/Applications/Xcode_15.0.app"
          /usr/bin/xcodebuild -version
          
      - name: Build Loop.app
        run: |
          sh ./resources/build_loop.sh
          
      - name: Codesign Loop.app
        uses: apple-actions/import-codesign-certs@v2
        with: 
          p12-file-base64: ${{ secrets.CERTIFICATES_P12 }}
          p12-password: ${{ secrets.CERTIFICATES_P12_PASSWORD }}
      
#       - name: Codesign executable
#         env: 
#           MACOS_CERTIFICATE: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
#           MACOS_CERTIFICATE_PWD: ${{ secrets.P12_PASSWORD }}
#         run: |
#           echo $MACOS_CERTIFICATE | base64 --decode > certificate.p12
          
#           # Make new keychain & unlock it
#           security create-keychain -p 12345678 build.keychain
#           security default-keychain -s build.keychain
#           security unlock-keychain -p 12345678 build.keychain
          
#           # Add codesign certificate to keychain 
#           security import certificate.p12 -k build.keychain -P $MACOS_CERTIFICATE_PWD -T /usr/bin/codesign
          
#           security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k 12345678 build.keychain
          
#           # Codesign Loop
#           /usr/bin/codesign --force -s <identity-id> ./path/to/you/app -v
          
      - name: Zip Loop.app
        run: |
          cd Release/
          ditto -c -k --sequesterRsrc --keepParent Loop.app Loop-.zip
          
          # Testing purposes
          git rev-parse --short HEAD
          
      - name: Upload achived app
        uses: actions/upload-artifact@v3.1.2
        with:
          name: app
          path: Release/Loop.zip
